---
title: "combined_all"
output: html_document
date: "2024-12-11"
---

```{r}
# Load necessary libraries for data manipulation and analysis
library(tidyr)       # Tools for data tidying
library(stringr)     # String manipulation
library(tidyverse)   # Collection of packages for data science
library(dplyr)       # Data manipulation

# Set the root directory and load census and election datasets
root_dir = paste0(dirname(getwd()), '/') 
census_data_orig = readRDS(paste0(root_dir, 'data/census_data/election_census.rds'))  # Load original census data
election_data_orig = readRDS(paste0(root_dir, "data/election_data/election_data.rds"))  # Load original election data

```

```{r}
# Clean and prepare the election data
election_data = election_data_orig |>
  select(-candidate) |>  # Remove candidate column as it is not needed
  rename(STNAME = state, CTYNAME = county_name, YEAR = year) |>  # Rename columns for consistency with census data
  mutate(CTYNAME = toupper(CTYNAME))  |>  # Convert county names to uppercase for uniformity
  group_by(STNAME, CTYNAME, party, YEAR, state_po, totalvotes, county_fips) |>  # Group data for aggregation
  summarise(candidatevotes = sum(candidatevotes, na.rm = TRUE),  # Aggregate votes by candidate and party
            .groups = "drop") |>
  pivot_wider(names_from = party, values_from = candidatevotes)  # Reshape data to have separate columns for each party


census_data = census_data_orig |>
  select(-STATE) |>
  select(-COUNTY) |>
  select(-YEAR_NUM) |>
  arrange(STNAME, CTYNAME, YEAR, AGEGRP)|>
  filter(DATE != "4/1/2000 base estimate")


# Clean and prepare the census data
census_data = census_data_orig |>
  select(-STATE, -COUNTY, -YEAR_NUM) |>  # Remove unnecessary columns
  arrange(STNAME, CTYNAME, YEAR, AGEGRP) |>  # Order data for better readability
  filter(DATE != "4/1/2000 base estimate")  # Exclude base estimates for consistency

# Define columns and age groups for further processing
pop_columns = c("TOT_MALE", "TOT_FEMALE", "WA_MALE", "WA_FEMALE", "BA_MALE", "BA_FEMALE", 
                "IA_MALE", "IA_FEMALE", "AA_MALE", "AA_FEMALE", "TOM_MALE", "TOM_FEMALE", 
                "NH_MALE", "NH_FEMALE", "H_MALE", "H_FEMALE")
age_grps = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "99")

# Transform and summarize the census data
census_data = census_data |>
  mutate(CTYNAME = toupper(str_trim(str_replace(CTYNAME, "\\s+[^\\s]+$", "")))) |>  # Clean and standardize county names
  mutate(STNAME = toupper(STNAME))  |>  # Convert state names to uppercase for consistency
  pivot_wider(names_from = AGEGRP, values_from = TOT_POP) |>  # Reshape data to spread age group columns
  select(-0) |>  # Remove unnecessary columns
  group_by(STNAME, CTYNAME, YEAR, DATE) |>  # Group data for aggregation
  summarise(
    across(all_of(pop_columns), ~ sum(.x[1:18])),  # Aggregate population columns by age groups
    across(all_of(age_grps), ~ first(.x[!is.na(.x)])),  # Handle missing values
    .groups = "drop") |>
  rename(TOTAL_POP = "99", AGE_0_4 = "1", AGE_5_9 = "2", AGE_10_14 = "3", AGE_15_19 = "4",
         AGE_20_24 = "5", AGE_25_29 = "6", AGE_30_34 = "7", AGE_35_39 = "8", AGE_40_44 = "9",
         AGE_45_49 = "10", AGE_50_54 = "11", AGE_55_59 = "12", AGE_60_64 = "13",
         AGE_65_69 = "14", AGE_70_74 = "15", AGE_75_79 = "16", AGE_80_84 = "17", AGE_85_PLUS = "18") |>
    mutate(YEAR = as.integer(YEAR))  # Convert year to integer format
 
  
```

```{r}
# Combine the census and election data
combined_data = census_data |> 
  inner_join(election_data, by = c("STNAME", "CTYNAME", "YEAR"))  # Merge datasets based on common columns

```


```{r}
# Combine the census and election data
combined_data = census_data |> 
  inner_join(election_data, by = c("STNAME", "CTYNAME", "YEAR"))  # Merge datasets based on common columns

```










```{r}
age_cols = c("AGE_0_4", 
         "AGE_5_9", 
         "AGE_10_14", 
         "AGE_15_19",
         "AGE_20_24",
         "AGE_25_29",
         "AGE_30_34",
         "AGE_35_39",
         "AGE_40_44",
         "AGE_45_49",
         "AGE_50_54",
         "AGE_55_59",
         "AGE_60_64",
         "AGE_65_69",
         "AGE_70_74",
         "AGE_75_79",
         "AGE_80_84",
         "AGE_85_PLUS")

# Create a dataset with demographic percentages
percents_data <- combined_data |>
  mutate(
    PERC_WHITE = (WA_MALE + WA_FEMALE) / TOTAL_POP,  # Percentage of White population
    PERC_BLACK = (BA_MALE + BA_FEMALE) / TOTAL_POP,  # Percentage of Black population
    PERC_INDIG = (IA_MALE + IA_FEMALE) / TOTAL_POP,  # Percentage of Indigenous population
    PERC_ASIAN = (AA_MALE + AA_FEMALE) / TOTAL_POP,  # Percentage of Asian population
    PERC_TWOMO = (TOM_MALE + TOM_FEMALE) / TOTAL_POP,  # Percentage of Two or More Races
    PERC_HISPA = (H_MALE + H_FEMALE) / TOTAL_POP,  # Percentage of Hispanic population
    PERC_MALE = TOT_MALE / TOTAL_POP,  # Percentage of male population
    PERC_FEMALE = TOT_FEMALE / TOTAL_POP,  # Percentage of female population
    PERC_REPUBLICAN = REPUBLICAN / TOTAL_POP,  # Republican votes as a percentage of total population
    PERC_DEMOCRAT = DEMOCRAT / TOTAL_POP,  # Democratic votes as a percentage of total population
    PERC_OTHER = OTHER / TOTAL_POP,  # Other votes as a percentage of total population
    PERC_MINORITY = 1 - PERC_WHITE  # Percentage of minority population
  ) |>
  rename(TOTAL_VOTES = totalvotes) |>  # Rename total votes column
  mutate(across(all_of(age_cols), ~ .x / TOTAL_POP)) |>  # Calculate age group percentages
  select(STNAME, CTYNAME, county_fips, YEAR, TOTAL_POP, PERC_WHITE, PERC_BLACK, PERC_INDIG, 
         PERC_ASIAN, PERC_TWOMO, PERC_MINORITY, PERC_HISPA, PERC_MALE, PERC_FEMALE, 
         all_of(age_cols), TOTAL_VOTES, PERC_REPUBLICAN, PERC_DEMOCRAT, PERC_OTHER) |>
  arrange(STNAME, CTYNAME, YEAR)  # Arrange data for better readability


```

```{r}
# Save the combined and percentage datasets as CSV and RDS files
write.csv(combined_data, file = paste0(root_dir, 'data/combined_data.csv'), row.names = TRUE)
saveRDS(combined_data, file = paste0(root_dir,'data/combined_data.rds'))
write.csv(percents_data, file = paste0(root_dir,'data/percents_data.csv'), row.names = TRUE)
saveRDS(percents_data, file = paste0(root_dir,'data/percents_data.rds'))

```
